name: Generate Sporcafe M3U

# Workflow tetikleyici
on:
  schedule:
    - cron: '0 8 * * *'  # Her gün saat 08:00 UTC
  workflow_dispatch:      # Manuel tetikleme

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # İstediğin Python versiyonu

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run generator
        run: python sporcafe_generator.py

      - name: Commit & Push updated files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add sporcafe.m3u channels.json
          git commit -m "Update M3U and JSON via GitHub Action" || echo "No changes to commit"
          git push
